site_name: Manual Testing Guide
theme:
  name: material  # This gives a modern sidebar navigation
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
theme:
  name: readthedocs  # This gives a modern sidebar navigation

nav:
  - Home: index.md
  - Course Topics:
      - Course Topics: course_overview.md
